### ISSUE TITLE
Mais artigos #pelamor

### ISSUE THREAD

**Issue by woliveiras** [femug-abc/slack#1]
Levando em conta uma conversa no Slack, decidimos traduzir alguns artigos técnicos para movimentar um pouco a comunidade.
Essa Issue é para discutir sobre isso.

Pontos a serem analisados:
- Como vamos fazer?
- Quais sites legais para traduzir os artigos?
- Onde vamos deixar os artigos traduzidos?

**Comment by woliveiras** [comment]
Acho que podemos colocar em algumas issues os artigos maneiros, cada um vai pegando e traduzindo.
Os artigos poderiam ficar no Tableless, que é um local com boa visibilidade e muito acesso, então ajudaríamos muito a comunidade ou nos nossos blogs pessoais. 

Eu voto pelo Tableless!

**Comment by akfzambrana** [comment]
:+1: pro tableless, mas acho q tem q conversar com o diego antes pra ver se podemos fazer isso de colocar artigos "não originais" so traduzidos, pq acho q tem alguma regra la sobre isso :wink:

**Comment by woliveiras** [comment]
Opa, verdade! Vou dar um toque pra ele pra já!

**Comment by willianribeiro** [comment]
Seguindo

**Comment by woliveiras** [comment]
Galera, o Eis falou que é só colocar no final do artigo a origem do mesmo. No Tableless tem até uma categoria `traduções`. Bora fazer isso?

**Comment by woliveiras** [comment]
Criado: [Translations](https://github.com/femug-abc/femug-abc/tree/master/projects/translations)
