### ISSUE TITLE
Separação dos canais

### ISSUE THREAD

**Issue by woliveiras** [femug-abc/slack#2]
Devido ao crescimento do Grupo, os assuntos em #papo-tecnico estão ficando meio perdidos.

Seria interessante separarmos o canal por assuntos mais específicos para facilitar uma possível busca.

Ex.:
- `HTML/CSS` : Para falar tudo sobre HTML e CSS incluindo pre processadores e template engines.
- `JavaScript`: Assuntos relacionados a JS tanto no Front, quanto automatizadores como Gulp/Grunt e relacionados.
- `Back End`: PHP, Python, Banco de Dados, Nodejs, etc. Como não falamos tanto sobre linguagens específicas, podemos falar tudo sobre Back End nesse canal.

**Comment by willianribeiro** [comment]
Apoio! :+1: 
Eu tava pensando isso essa semana, pra mim faz muito sentido. Cada um vai direto no canal que mais se identifica.

**Comment by woliveiras** [comment]
Essa ordem dos canais que eu propus é maneira, mano @willianribeiro?

**Comment by willianribeiro** [comment]
Sim, pra mim faz sentido, @woliveiras.

**Comment by carmona** [comment]
:heavy_plus_sign: :one: :+1:  @woliveiras

**Comment by woliveiras** [comment]
Feito galera! 

[Atualização dos canais no Slack](https://github.com/femug-abc/slack/blob/master/canais.md)
