### ISSUE TITLE
markdown links

### ISSUE THREAD

**Issue by carmona** [femug-abc/slack#3]
Adicionar arquivos .md para receber os links inseridos nos channels, um arquivo por channel nos seguintes: 
- [geral](https://femugabc.slack.com/messages/geral/)
- [front-end](https://femugabc.slack.com/messages/front-end/)
- [back-endl](https://femugabc.slack.com/messages/back-end/)
- [off-topic](https://femugabc.slack.com/messages/off-topic/)

Imagino que essa integração possa ser feita via Zapier ou com um bot hospedado no heroku (neste caso, seria bom termos um repositório só pra esse bot)

Passando a bola pro @woliveiras agora =)

**Comment by woliveiras** [comment]
Valeu mano! :D
